-- 코드를 입력하세요
SELECT A.FLAVOR
-- B는 같은 맛끼리 묶는 과정이 필요함.
FROM FIRST_HALF A JOIN ( SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR ) B
ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3