-- 코드를 입력하세요
SELECT INFO.REST_ID,INFO.REST_NAME,
INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, 
ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS REVIEW INNER JOIN REST_INFO AS INFO
ON REVIEW.REST_ID = INFO.REST_ID
GROUP BY REVIEW.REST_ID
HAVING INFO.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, INFO.FAVORITES DESC